{{- if .Values.enterprise.enabled }}
{{- range .Values.tenants }}
---
apiVersion: cairnobs.io/v1alpha1
kind: Tenant
metadata:
  name: {{ .name }}
  labels:
    {{- include "cairnobs.labels" $ | nindent 4 }}
spec:
  displayName: {{ .displayName | default .name | quote }}
  suspended: {{ .suspended | default false }}
{{- end }}
{{- end }}
