// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: sentry/logs/v1/logs.proto

package logsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogIngest_PushBatch_FullMethodName = "/sentry.logs.v1.LogIngest/PushBatch"
)

// LogIngestClient is the client API for LogIngest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LogIngest is the service agents use to ship batched log records to the
// ingest service over mTLS. Phase 0: single unary batch push. Streaming
// (client-streaming for continuous shipping) is a likely Phase 1 upgrade
// once backpressure/flow-control behavior is characterized.
type LogIngestClient interface {
	PushBatch(ctx context.Context, in *PushBatchRequest, opts ...grpc.CallOption) (*PushBatchResponse, error)
}

type logIngestClient struct {
	cc grpc.ClientConnInterface
}

func NewLogIngestClient(cc grpc.ClientConnInterface) LogIngestClient {
	return &logIngestClient{cc}
}

func (c *logIngestClient) PushBatch(ctx context.Context, in *PushBatchRequest, opts ...grpc.CallOption) (*PushBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushBatchResponse)
	err := c.cc.Invoke(ctx, LogIngest_PushBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogIngestServer is the server API for LogIngest service.
// All implementations must embed UnimplementedLogIngestServer
// for forward compatibility.
//
// LogIngest is the service agents use to ship batched log records to the
// ingest service over mTLS. Phase 0: single unary batch push. Streaming
// (client-streaming for continuous shipping) is a likely Phase 1 upgrade
// once backpressure/flow-control behavior is characterized.
type LogIngestServer interface {
	PushBatch(context.Context, *PushBatchRequest) (*PushBatchResponse, error)
	mustEmbedUnimplementedLogIngestServer()
}

// UnimplementedLogIngestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogIngestServer struct{}

func (UnimplementedLogIngestServer) PushBatch(context.Context, *PushBatchRequest) (*PushBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushBatch not implemented")
}
func (UnimplementedLogIngestServer) mustEmbedUnimplementedLogIngestServer() {}
func (UnimplementedLogIngestServer) testEmbeddedByValue()                   {}

// UnsafeLogIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogIngestServer will
// result in compilation errors.
type UnsafeLogIngestServer interface {
	mustEmbedUnimplementedLogIngestServer()
}

func RegisterLogIngestServer(s grpc.ServiceRegistrar, srv LogIngestServer) {
	// If the following call panics, it indicates UnimplementedLogIngestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogIngest_ServiceDesc, srv)
}

func _LogIngest_PushBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogIngestServer).PushBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogIngest_PushBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogIngestServer).PushBatch(ctx, req.(*PushBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogIngest_ServiceDesc is the grpc.ServiceDesc for LogIngest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogIngest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentry.logs.v1.LogIngest",
	HandlerType: (*LogIngestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushBatch",
			Handler:    _LogIngest_PushBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sentry/logs/v1/logs.proto",
}
